### ISSUE TITLE
what means outer_joint_iter

### ISSUE THREAD

**Issue by llianxu** [cvg/nice-slam#62]
Thanks for the nice project！
I am confused about the meaning of **outer_joint_iter**  in **mapper.py** and would like to consult you

**Comment by Zzh2000** [comment]
Hi, 
Thanks for your interest in our project!
outer_joint_iter gives the user an option to change the selected keyframes during mapping. Within each outer_joint_iter, the selected keyframes will not change. outer_joint_iter is 3 for iMAP* since it changes the selected keyframes during mapping 3 times.
