### ISSUE TITLE
How could I get unseen.npy of cull_replica_mesh?

### ISSUE THREAD

**Issue by TwiceMao** [cvg/nice-slam#89]
You provided cull_mesh.py to get cull_replica_mesh, but how to get the corresponding unseen.npy?

**Comment by Zzh2000** [comment]
unseen.npy is the unseen vertices stored in npy file format.

**Comment by TwiceMao** [comment]
@Zzh2000  If I don't have unseen.npy how to use the eval_recon.py you provided？

**Comment by Zzh2000** [comment]
If you are trying to test on some other datasets other than Replica, you can easily generate unseen.npy yourself.

**Comment by TwiceMao** [comment]
@Zzh2000 For me, I am using the Replica dataset, but it is a different trajectory pose. After I use cull_mesh.py to get the corresponding cull_mesh, I don’t know how to get your so-called unseen points, because the number of vertices in cull_mesh.ply and the original mesh.ply is the same.

**Comment by colin-de** [comment]
I still didn't get how the `unseen.npy` is generated, and it turns out that the unseen vertices from office_0 in replica look like this
![image](https://github.com/cvg/nice-slam/assets/50893130/a8cef77d-067c-4e99-84fa-cdac703826a3)
which is not the unseen part of the point cloud(mesh). Could you please elaborate more about the setting of getting `unseen.npy` ? @Zzh2000
