### ISSUE TITLE
Much higher mapping time during test time. 

### ISSUE THREAD

**Issue by saunair** [cvg/nice-slam#9]
Hey Authors, 
Firstly, thanks for the ease of use of your code. Running it was almost seamless on multiple machines / datasets!

Although, after timing the code for the Apartment datataset, the mapping step seems to be considerably slower on my machine (100ms vs 500ms).
The CPU is an `i9-10900X CPU @ 3.70GHz` and `GPU RTX 3090` .  (All 10 cores / 20 threads seem to be used during training/inference)
The paper claims to be using a `3.80GHz Intel i7-10700K CPU` which only has 8 cores of an older generation. 

I doubt the small difference in the clock frequecy can cause a difference of 5 fold. What do you guys think it could be?

**Comment by Zzh2000** [comment]
Hi, 
Thanks for your interest in our work! 
The table 4 in our paper is using the same iteration and pixel samples as the table in iMAP paper. (since iMAP did not open source, we can only compare in that way) The goal is to show the benefit of our scene representation, not to report the runtime on each dataset. For different datasets, we use different iterations and pixel samples shown in implementation details. In our re-implementation of iMAP (iMAP*), we give much more iterations and pixel samples, to make a more than fair comparision.
